apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: bpagadala
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/bpagadala-harbor-project/db@sha256:281f389ebbadb1fa3a2098ea2dc7561c4e4fde36bb45dd1f2db7ab3c705f509a
        ports:
        - containerPort: 5432
